apiVersion: apps/v1
kind: Deployment
metadata:
  name: hass-deployment
  labels:
    app: hass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hass
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hass
    spec:
      hostNetwork: true
      containers:
        - name: hass
          image: ghcr.io/home-assistant/home-assistant:2024.3.3
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: pvc
              mountPath: /config
              subPath: hass
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: microk8s-pvc

# when multinode use:
# [1] https://docs.openebs.io/
# [2] https://microk8s.io/docs/addon-openebs
