apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      initContainers:
        - name: install-hacs-when-needed
          image: alpine:latest
          command:
            - sh
            - -c
            - if [ ! -d /config/custom_components/hacs ]; then apk add --no-cache bash wget && wget -O - https://get.hacs.xyz | bash -; fi
          volumeMounts:
            - mountPath: /config
              name: pvc
              subPath: hass
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:2024.4.0
          ports:
            - containerPort: 8123
          volumeMounts:
            - name: pvc
              mountPath: /config
              subPath: hass
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: microk8s-pvc
# when multinode use:
# [1] https://docs.openebs.io/
# [2] https://microk8s.io/docs/addon-openebs
