kind: Service
apiVersion: v1
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30123
  selector:
    app: homeassistant
  type: NodePort
