apiVersion: v1
kind: Service
metadata:
  name: adguard
  annotations:
    metallb.universe.tf/address-pool: default-addresspool
spec:
  selector:
    app: adguard
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http-initial
    nodePort: 30000
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
    nodePort: 30080
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns
  type: LoadBalancer
